# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Code check

on:
  pull_request:
    branches:
      - main

jobs:
  cicd:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install libraries
      run: |
        pushd website/
        npm install
        popd
        npm install

    - name: install nr1 cli
      run: curl -s https://cli.nr-ext.net/installer.sh | sudo bash

    - name: Lint check
      run: npm run eslint-check

    - name: Build data file
      run: npm run generator

    - name: Build website
      run: npm run build-website

    - name: Build nerdlet
      run: npm run build

  validate-nerdpack:
    name: validate nerdpack
    needs: checkout-and-build-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Validate Open Source Files
        uses: newrelic/validate-nerdpack-action@v1

      - name: Install NR1 CLI
        run: |
          curl -s https://cli.nr-ext.net/installer.sh | sudo bash
      - name: Validate Nerdpack Schema
        run: |
          nr1 nerdpack:validate
